### ISSUE TITLE
Localization issues with firefox/channel/index.lang

### ISSUE THREAD

**Issue by splewako** [mozilla-l10n/www.mozilla.org#109]
On https://www-demo1.allizom.org/pl/firefox/channel/desktop/
- Firefox Beta automatically sends feedback to Mozilla. Learn more
- Firefox Developer Edition automatically sends feedback to Mozilla. Learn more
- Firefox Nightly automatically sends feedback to Mozilla. Learn more

On https://www-demo1.allizom.org/pl/firefox/channel/android/
- Firefox Beta automatically sends feedback to Mozilla. Learn more
- Firefox Aurora automatically sends feedback to Mozilla. Learn more

"Learn more" links translations are incorrectly taken from general file - as part of paragraph translation they should be in firefox/channel/index.lang file.

**Comment by splewako** [comment]
On https://www-demo1.allizom.org/pl/firefox/channel/*/ pages "Android" and "iOS" navigation links are unlocalizable.

**Comment by flodolo** [comment]
The `Learn more` string is shared across several pages, and we never got report of the issue. So, in order to understand: the string is translated as `Więcej informacji` in main.lang, how would it be translated in this context? Or are you asking to make it part of the previous string?

iOS and Android are not exposed on purpose, since they're trademarks. How should they be in Polish? Do you need to decline them?

**Comment by splewako** [comment]
> The Learn more string is shared across several pages, and we never got report of the issue. So, in order to understand: the string is translated as Więcej informacji in main.lang, how would it be translated in this context? Or are you asking to make it part of the previous string?

It is translated as stand alone string and here it clearly isn't stand alone but part of the sentence. Example of how it should be done could be spotted on https://www-dev.allizom.org/pl/firefox/channel/ and https://github.com/mozilla-l10n/www.mozilla.org/blob/master/en-US/firefox/channel.lang#L32 (which also may explain why it wasn't problem reported earlier).

> iOS and Android are not exposed on purpose, since they're trademarks. How should they be in Polish? Do you need to decline them?

It would be better to use them in form "For Android/iOS" in Polish, the same way as DESKTOP was translated in main.lang.

**Comment by flodolo** [comment]
So, you're asking to make the `Learn more` part of the entire string. Aren't you [using](https://github.com/mozilla-l10n/www.mozilla.org/blob/master/pl/firefox/channel.lang#L29) the same translation for `Learn more`? Or you mean that you need the period at the end?

I can't fix that in the .lang file, you'd need to file a bug on www.mozilla.org::Pages and content, blocking https://bugzilla.mozilla.org/show_bug.cgi?id=1299947
But that would probably be out of scope for the launch, since we have a hard deadline for localization.

I'm going to expose the other 2 strings, and mark them as `{ok}` for all locales. That way complete locales are not marked as incomplete, but you can still update them if you need to.

**Comment by flodolo** [comment]
Menu strings are exposed in https://github.com/mozilla-l10n/www.mozilla.org/commit/2d2f83332eb95568baf03b017818fc26b88cde86#diff-7d8db872231617f1531c9cf0e8106615

As said, the other issue can't be fixed here. You would need to file a bug to get the string changed in the template, even if I'm still failing to understand the issue (I assume it's the missing final period).

**Comment by splewako** [comment]
> You would need to file a bug to get the string changed in the template, even if I'm still failing to understand the issue (I assume it's the missing final period).

https://bugzilla.mozilla.org/show_bug.cgi?id=1305009 and yes, in this case is about the final period. Thank you.
