### ISSUE TITLE
Invalid closing anchor tag in "th" locale in locale/th/firefox/features/password-manager.lang:46

### ISSUE THREAD

**Issue by pdehaan** [mozilla-l10n/www.mozilla.org#308]
Via some random bash grepping:

```sh
$ grep -irn "/>" locale | egrep -v "<br\s?\/>"

locale/th/firefox/features/password-manager.lang:46:ได้สายดำด้านความมั่นคงเส้นที่สองด้วย<a href="%(addons)s">ส่วนเสริม<a/>ตัวจัดการการรหัสผ่านชุดใหญ่ของ Firefox เลือกตัวที่เป็นตัวโปรดอยู่แล้วหรือในระดับถัดไปจากคะแนนและรีวิวจากชุมชนผู้เชี่ยวชาญ

locale/th/firefox/features/password-manager.lang:53:ได้สายดำด้านความมั่นคงเส้นที่สองด้วย<a href="%(addons)s">ส่วนเสริม<a/>ตัวจัดการการรหัสผ่านชุดใหญ่ของ Firefox ใช่ตัวโปรด เช่น <a href="%(lastpass)s">LastPass</a> หรือหาตัวจัดการรหัสผ่านตัวเก่งจากคะแนนและรีวิวจากชุมชน
```

https://github.com/mozilla-l10n/bedrock-l10n/blob/64ff442bb9de464ae1d86a548a0d98c134573090/th/firefox/features/password-manager.lang#L46

Note that the tag is `<a href="%(addons)s">ส่วนเสริม<a/>` and has a `<a/>` instead of `</a>`.

**NOTE:** The error is also on L53, but that seems to be an obsolete string, so whatever.

---

https://www-dev.allizom.org/th/firefox/features/password-manager/

![เบราว์เซอร์_Firefox__ตัวจัดการรหัสผ่านที่เร็วและง่าย](https://user-images.githubusercontent.com/557895/60369238-cda15000-99a7-11e9-8669-d02d9c6e9d9f.png)

**Comment by flodolo** [comment]
Fixed in [Pontoon](https://pontoon.mozilla.org/translate/th/mozillaorg/all-resources/?search=%E0%B9%84%E0%B8%94%E0%B9%89%E0%B8%AA%E0%B8%B2%E0%B8%A2%E0%B8%94%E0%B8%B3%E0%B8%94%E0%B9%89%E0%B8%B2%E0%B8%99%E0%B8%84%E0%B8%A7%E0%B8%B2%E0%B8%A1%E0%B8%A1%E0%B8%B1%E0%B9%88%E0%B8%99%E0%B8%84%E0%B8%87%E0%B9%80%E0%B8%AA%E0%B9%89%E0%B8%99%E0%B8%97%E0%B8%B5%E0%B9%88%E0%B8%AA%E0%B8%AD%E0%B8%87%E0%B8%94%E0%B9%89%E0%B8%A7%E0%B8%A2&string=169616)
